services:

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: acme_tarifas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: franmarinozzi/back-acme-tarifas:latest
    container_name: backend-app
    depends_on:
      - db
    ports:
      - "7071:7070"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/acme_tarifas
      - DB_DRIVER=org.postgresql.Driver
      - DB_USER=root
      - DB_PASS=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: franmarinozzi/front-acme-tarifas:latest
    container_name: frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: